jaffle_shop:
  outputs:
    dev:
      dbname: jaffle_shop
      host: postgres
      pass: airflow
      port: 5432
      schema: jaffle_shop
      threads: 4
      type: postgres
      user: airflow
  target: dev
