olist_ecommerce:
  outputs:
    dev:
      dbname: olist
      host: postgres
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      port: 5432 # Your default database port here
      schema: olist
      threads: 4
      type: postgres
  target: dev
